export const FORM_FLAG = "````";
export const INLINE_SPLIT = "|";
export const END_SCRIPT_TAG = "</script>";
export const CLOSE_SCRIPT_REG = /<\/script>(?!"|')/;
export const FORM_STATE = "const formState = reactive(object);";
export const RULES = "const rules = {};";
export const ANT_DESIGN_VUE = "Ant Design Vue";
export const VUE3_SETUP_REG = /<script\s+(\w+="\w+"\s+)?setup/;
export const VUE3_SCRIPT_SELECTOR = "<script setup></script>";
export const VUE2_SCRIPT_SELECTOR = "<script></script>";
export const TEMPLATE_SELECTOR = "<template></template>";
export const FORM_SELECTOR = "platform.Selector";
export const ZERO_INDENT_START_TAGS = ["<template", "<script", "<style"];
